#!/bin/zsh

# tmux 管理命令脚本

echo "Binance监控系统 - tmux 管理命令"
echo "========================================"

echo ""
echo "📋 可用命令:"
echo ""
echo "1. 启动监控系统:"
echo "   ./start_tmux.sh"
echo ""
echo "2. 连接到监控会话:"
echo "   tmux attach -t binance_monitor"
echo ""
echo "3. 查看所有tmux会话:"
echo "   tmux ls"
echo ""
echo "4. 从会话分离（不停止程序）:"
echo "   按 Ctrl+B，然后按 D"
echo ""
echo "5. 停止监控系统:"
echo "   tmux kill-session -t binance_monitor"
echo ""
echo "6. 重启监控系统:"
echo "   tmux kill-session -t binance_monitor && ./start_tmux.sh"
echo ""
echo "7. 在会话中创建新窗口:"
echo "   按 Ctrl+B，然后按 C"
echo ""
echo "8. 切换窗口:"
echo "   按 Ctrl+B，然后按 数字键"
echo ""
echo "💡 使用技巧:"
echo "- 启动后可以立即分离会话: Ctrl+B, D"
echo "- 需要查看运行状态时重新连接: tmux attach -t binance_monitor"
echo "- 即使断开SSH连接，程序也会继续运行"
echo "- 服务器重启后需要重新启动会话"